export const ORDER_FINANCIAL_STATUS = {
    PAID: 'PAID',
    PENDING: 'PENDING',
    REFUNDED: 'REFUNDED',
    VOIDED: 'VOIDED',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
};

export const ORDER_FULFILLMENT_STATUS = {
    FULFILLED: 'FULFILLED',
    UNFULFILLED: 'UNFULFILLED',
    PARTIALLY_FULFILLED: 'PARTIALLY_FULFILLED',
    SCHEDULED: 'SCHEDULED',
    ON_HOLD: 'ON_HOLD',
};

export const PRODUCT_STATUS = {
    ACTIVE: 'active',
    DRAFT: 'draft',
    ARCHIVED: 'archived',
};

export const ORDER_FINANCIAL_STATUS_BADGE = {
    [ORDER_FINANCIAL_STATUS.PAID]: 'success',
    [ORDER_FINANCIAL_STATUS.PENDING]: 'attention',
    [ORDER_FINANCIAL_STATUS.REFUNDED]: 'warning',
    [ORDER_FINANCIAL_STATUS.VOIDED]: 'critical',
    [ORDER_FINANCIAL_STATUS.PARTIALLY_PAID]: 'info',
    [ORDER_FINANCIAL_STATUS.PARTIALLY_REFUNDED]: 'warning',
};

export const ORDER_FULFILLMENT_STATUS_BADGE = {
    [ORDER_FULFILLMENT_STATUS.FULFILLED]: 'success',
    [ORDER_FULFILLMENT_STATUS.UNFULFILLED]: 'attention',
    [ORDER_FULFILLMENT_STATUS.PARTIALLY_FULFILLED]: 'info',
    [ORDER_FULFILLMENT_STATUS.SCHEDULED]: 'info',
    [ORDER_FULFILLMENT_STATUS.ON_HOLD]: 'warning',
};

export const PRODUCT_STATUS_BADGE = {
    [PRODUCT_STATUS.ACTIVE]: 'success',
    [PRODUCT_STATUS.DRAFT]: 'attention',
    [PRODUCT_STATUS.ARCHIVED]: 'warning',
};
